{% set name = "vscode-python" %}
{% set version = "2023.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/microsoft/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 7ed586dd7d871f3db18df79b22fbbcd095daab5b91928108ccf4af8723b9bc1b

build:
  number: 0
  skip: true  # [win]
  skip_compile_pyc:
    - '*/python/debugpy/_vendored/*'
  ignore_run_exports:
    # node-canvas is built but not installed, so ignore its dependencies
    - cairo
    - giflib
    - libglib
    - libjpeg-turbo
    - pango
    - pixman

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - pip
    - packaging
    - nodejs 16
    - code-server >=3.9.2
    - vscode-jupyter
    # As part of the build, we are compiling node-canvas from source
    - pixman
    - giflib
    - glib
    - cairo
    - pango
    - libjpeg-turbo
  run:
    - python
    - code-server >=3.9.2
    - vscode-jupyter

test:
  commands:
    - code-server --list-extensions --show-versions | grep ms-python.python@{{ version }}

about:
  home: https://github.com/microsoft/vscode-python
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyNotices-Repository.txt
  summary: Python extension for Visual Studio Code

extra:
  recipe-maintainers:
    - conda-forge/code-server
